sudo: false

language: rust

before_install:
    - wget http://influxdb.s3.amazonaws.com/influxdb_0.9.4.1_amd64.deb
    - dpkg-deb -x influxdb_0.9.4.1_amd64.deb $HOME
    - $HOME/opt/influxdb/versions/0.9.4.1/influxd > $HOME/influx.log 2>&1 &

after_script:
    - cat $HOME/influx.log

rust:
    - nightly
    - beta
    - stable

matrix:
    allow_failures:
        - rust: nightly
        - rust: beta
        - env: VAULT_BRANCH=head TRAVIS_CARGO_NIGHTLY_FEATURE=""